car_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 25 

  joint_position_controller:
    joint1_position_controller:
      type: position_controllers/JointPositionController
      joint: front_right_joint
      pid: {p: 100,i: 0.01,d: 10}
